AlejandroDiBattista/Lab4-C5

practicos/50 - 58866 - Velázquez, Tobias Alejo/ejercicio.ipynb

tp1-vtobias

---

practicos/37 - 52142 - Reyes Gordillo, Rodrigo M/tp2/Ejercicio.ipynb

Se carga resolucion de problemas dados en Trabajos practicos 1 y 2.-

Carga de Tp 1 y 2

---

practicos/08 - 58895 - Flores Gonzalez, Tomás Agustín/tp2/Ejercicio.ipynb

Tp2-Flores_Tomas

---

practicos/08 - 58895 - Flores Gonzalez, Tomás Agustín/tp1/ejercicio.ipynb

Tp1-Flores_Tomas

---

practicos/30 - 58729 - Lovey, Mathias Exequiel/tp1/ejercicio.ipynb

TP1- Lovey (Corrección)

---

practicos/27 - 59152 - Lopez Chipoloni, Agustin/tp3/ejercicio.ipynb

TP3-CHIPOLONI

---

practicos/08 - 58895 - Flores Gonzalez, Tomás Agustín/tp3/ejercicio.ipynb

TP3-Flores_Tomas

---

practicos/37 - 52142 - Reyes Gordillo, Rodrigo M/tp3/ejercicio.ipynb

Ejercicio 1

---

practicos/30 - 58729 - Lovey, Mathias Exequiel/tp3/ejercicio.ipynb

TrabajoPracticoN°3-LoveyMathias

---

practicos/54 - 55600 - Cañete Jacobo, Juan Manuel/tp5/ejercicio.ipynb

Tp5 -Canete juan manuel

---

practicos/29 - 59726 - Lopez, Fausto Agustin/tp6/ejercicio.ipynb

Buenas profesor, le escribo una descripcion debido a que estuve experimentando un problema para importar las librerias desde el dia miercoles y no pude encontrarle una solucion, intente con el chat e incluso le pedi ayuda a una de mis compañeros con mayor conocimientos, y ni asi pude solucionarlo. Por lo que no pude probar los codigos, pero aun asi se lo mando. Espero poder verlo pronto para poder comprender el problema y poder solucionarlo

TP6-LópezFausto

---

practicos/27 - 59152 - Lopez Chipoloni, Agustin/tp7/ejercicio.py

TP7.CHIPOLONI

---

practicos/50 - 58866 - Velázquez, Tobias Alejo/tp8/ejercicio.py

app deployed
https://tp8-58866.streamlit.app/

tp8-tobias

---

practicos/26 - 58727 - Lazarte, Lucas/tp8/ejercicio.py

https://lazartelucas.streamlit.app

tp8-lazartelucas

---

practicos/15 - 59488 - González, Mariano Emanuel/tp8/ejercicio.py
practicos/15 - 59488 - González, Mariano Emanuel/tp8/requirements.txt

Trabajo Practico numero 8. Gonzalez, Mariano Emanuel

Segundo Parcial

---

practicos/06 - 55249 - Fernandez, Gonzalo Tomas/tp8/ejercicio.py

Solo deseo no desaprobar 😔... Confio que me fue bien, y que podré terminar el año en paz.

TP8 Fernandez Gonzalo Tomas 2

---

practicos/44 - 55870 - Stemberger, Emiliano/tp7/ejercicio.py

TP7-55870-EmilianoStemberger

---

practicos/35 - 59054 - Rahman Rintoul, Ramiro/tp8/ejercicio.py
practicos/35 - 59054 - Rahman Rintoul, Ramiro/tp8/requirements.txt

[Link Streamlit TP8](https://tp8-lab-c5-3hksyedewsvqjsvscna2pt.streamlit.app) <- Link directo para su prueba

TP8-RahmanRintoul-Ramiro

---

practicos/50 - 58866 - Velázquez, Tobias Alejo/tp7/ejercicio.py

tp7-vtobias

---

practicos/50 - 58866 - Velázquez, Tobias Alejo/tp8/ejercicio.py

feat: Cambios en ejercicio.py
Se cambio la estructura del proyecto. Se hicieron cambios en la forma de mostrar los datos del alumno a la original. Pequeños cambios en el diseño para hacerlo fiel al ejemplo dado. Cambio en la forma de mostrar los cambios porcentuales.

tp8-vtobias

---

practicos/37 - 52142 - Reyes Gordillo, Rodrigo M/tp8/ejercicio.py

-Se agrega App
-Se completa información alumno

Commit 1 TP8

---

practicos/37 - 52142 - Reyes Gordillo, Rodrigo M/tp8/ejercicio.py

Se agregan correcciones al codigo

TP8-Correccion

---

practicos/03 - 58773 - Ellí Salazar, Gerónimo/tp8/ejercicio.py

hola profe, el que se llama "2da corrección elli geronimo tp8" es la corrección correcta, el anterior esta mal, me olvide de corregir el margen, disculpe, gracias

tp8 corregido Elli Geronimo
